package com.boil.models;


import javax.validation.constraints.NotNull;
import javax.persistence.*;

/**
 * Created by songyu on 2017/4/21.
 */
@Entity
@Table(name = "tb_ms_db_objects")
public class DbObject {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    private long version_id;

    private String dialect;

    private String type;

    private String name;

    @Column(name = "ddl",length = 65535)
    private String ddl;


}
