package com.boil.models;


import javax.validation.constraints.NotNull;
import javax.persistence.*;
import java.util.Date;

/**
 * Created by songyu on 2017/4/21.
 */
@Entity
@Table(name = "tb_ms_db_objects")
public class DbObject {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    private long version_id;

    private long project_id;

    private String dialect;

    private String object_type;

    private String object_name;

    private Date created;

    private Date last_ddl_time;

    private String status;

    @Column(name = "ddl_text",length = 65535)
    private String ddl_text;

    private boolean enable;

    private String comments;

    public boolean isEnable() {
        return enable;
    }

    public void setEnable(boolean enable) {
        this.enable = enable;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public long getProject_id() {
        return project_id;
    }

    public void setProject_id(long project_id) {
        this.project_id = project_id;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getVersion_id() {
        return version_id;
    }

    public void setVersion_id(long version_id) {
        this.version_id = version_id;
    }

    public String getDialect() {
        return dialect;
    }

    public void setDialect(String dialect) {
        this.dialect = dialect;
    }

    public String getObject_type() {
        return object_type;
    }

    public void setObject_type(String object_type) {
        this.object_type = object_type;
    }

    public String getObject_name() {
        return object_name;
    }

    public void setObject_name(String object_name) {
        this.object_name = object_name;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getLast_ddl_time() {
        return last_ddl_time;
    }

    public void setLast_ddl_time(Date last_ddl_time) {
        this.last_ddl_time = last_ddl_time;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDdl_text() {
        return ddl_text;
    }

    public void setDdl_text(String ddl_text) {
        this.ddl_text = ddl_text;
    }
}
