package com.boil.models;


import javax.validation.constraints.NotNull;
import javax.persistence.*;

/**
 * Created by songyu on 2017/4/21.
 */
@Entity
@Table(name = "tb_ms_db_objects")
public class DbObject {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    private long version_id;

    @Column(name="dialect",nullable=false,length=100)
    private String dialect;

    @Column(name="type",nullable=false,length=100)
    private String type;

    @Column(name="name",nullable=false,length=200)
    private String name;


}
